name: Portfolio
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings
defaults:
  - scope:
      path: some-path
      layout: some_layout
    values:
      strip_title: true
